ame: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Sostituisci con il ramo che vuoi monitorare per il deploy (ad esempio, 'master' o 'main')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v3 # versione dell'azione actions/checkout

      # Impostazione di Node.js (attenzione alla versione)
      - name: Set up Node.js
        uses: actions/setup-node@v3 # Questa è la versione dell'azione di GitHub Action (V3)
        with:
          node-version: '22'  # Si può usare una versione diversa, node -v per verificare quella in uso

      # Installazione delle dipendenze
      - name: Install dependencies
        run: npm install

      # Costruzione del progetto
      - name: Build project
        run: npm run build

      # Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.2  # peaceiris/actions-gh-pages@v3 
        with:
          folder: build     # Cartella di output del build (per React è solitamente 'build')
          github_token: ${{ secrets.GITHUB_TOKEN }} 
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usa il token di GitHub per autenticarsi
        #  publish_dir: ./build